<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>giss-arch-microservice-parent</artifactId>
        <groupId>es.giss.arch</groupId>
        <version>7.4.0</version>
    </parent>

    <groupId>es.giss.poc.farc</groupId>
    <artifactId>poc-micrologger-far</artifactId>
    <version>1.0.0</version>

    <dependencies>

        <dependency>
            <groupId>es.giss.arch</groupId>
            <artifactId>giss-arch-starter-kafka</artifactId>
        </dependency>

    </dependencies>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>jacoco-check</id>
                            <goals>
                                <goal>check</goal>
                            </goals>
                            <configuration>
                                <excludes>
                                    <exclude>es/giss/poc/farc/**/*</exclude>
                                </excludes>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
